import { useI18n } from '../../lib/i18n'

// Every user-facing string of the play surfaces, in both languages.
const en = {
  lobby: {
    eyebrow: 'Game room',
    title: 'Pick a table',
    sub: 'Play with friends, with agents, or both. Chips are play money, always.',
    featured: 'Featured',
    holdemName: "Texas Hold'em",
    holdemSummary: 'No-limit poker for 2 to 9. Aoi deals; the agents bring their own styles.',
    playNow: 'Play now',
    newTable: 'New table',
    joinCode: 'Join with code',
    myGames: 'My games',
    community: 'Community',
    openTables: 'Open tables',
    myTables: 'My tables',
    noGames: 'Nothing here yet. Describe a game to Aoi in chat and the agents will build it.',
    noCommunity: 'No community games yet.',
    noTables: 'No tables right now.',
    seats: 'seats',
    plays: 'plays',
    by: 'by',
    open: 'Open',
    join: 'Join',
    loadError: 'Could not load the lobby. Retrying when you come back.',
    retry: 'Retry',
    status: { building: 'Building', draft: 'Draft', published: 'Published' },
  },
  newTable: {
    title: 'New table',
    game: 'Game',
    name: 'Table name',
    namePh: "Friday night hold'em",
    seats: 'Seats',
    seatN: 'Seat {n}',
    me: 'Me',
    agent: 'Agent',
    open: 'Open seat',
    openHint: 'for a friend',
    pickAgent: 'Pick an agent',
    options: 'Hold’em options',
    stack: 'Starting stack',
    sb: 'Small blind',
    bb: 'Big blind',
    double: 'Blinds double every',
    doubleUnit: 'hands (0 = never)',
    maxHands: 'Max hands',
    maxHandsHint: '0 = until one player has every chip',
    clock: 'Turn clock',
    noClock: 'No clock',
    create: 'Create table',
    creating: 'Creating…',
    cancel: 'Cancel',
    tight: 'Tight',
    aggr: 'Aggression',
    bluff: 'Bluff',
    talk: 'Talk',
  },
  join: {
    title: 'Join with code',
    ph: 'ABC123',
    go: 'Join',
    joining: 'Joining table…',
    failed: 'That code did not work.',
    back: 'Back to games',
  },
  detail: {
    rules: 'Rules',
    versions: 'Versions',
    playtest: 'Playtest',
    play: 'Play',
    seats: '{min}–{max} seats',
    hidden: 'Hidden information',
    perfect: 'Perfect information',
    games: 'games',
    avgTurns: 'avg turns',
    seatWins: 'seat wins',
    noRules: 'No rules written yet.',
    back: 'All games',
  },
  room: {
    loading: 'Taking a seat…',
    notFound: 'This table could not be found.',
    back: 'Games',
    leave: 'Leave',
    leaveConfirm: 'Leave this table? An agent will take over your seat.',
    leaveYes: 'Leave table',
    stay: 'Stay',
    spectating: 'Spectating',
    reconnecting: 'Reconnecting…',
    offline: 'Offline. Retrying…',
    live: 'Live',
    lobbyTitle: 'Waiting for players',
    invite: 'Invite code',
    copyLink: 'Copy invite link',
    copied: 'Copied',
    start: 'Start game',
    starting: 'Starting…',
    waitHost: 'Waiting for the host to start.',
    openSeat: 'Open seat',
    makeOpen: 'Open it',
    makeAgent: 'Seat an agent',
    host: 'Host',
    you: 'You',
    finished: 'Game over',
    rematch: 'Rematch',
    backToLobby: 'Back to games',
    abandoned: 'This table was closed.',
    chat: 'Chat',
    log: 'Log',
    players: 'Players',
    say: 'Say something…',
    send: 'Send',
    noChat: 'No messages yet. Say hi.',
    noLog: 'Nothing has happened yet.',
    agentBadge: 'AI',
    panel: 'Table chat',
    close: 'Close',
    moveFailed: 'Move rejected',
    stale: 'The table moved on; here is the latest.',
    rank: ['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th'],
    score: 'Score',
    tapVoice: 'Tap to hear Aoi',
  },
  holdem: {
    pot: 'Pot',
    side: 'Side pot',
    hand: 'Hand #{n}',
    handsLeft: '{n} left',
    blinds: 'Blinds {sb}/{bb}',
    fold: 'Fold',
    check: 'Check',
    call: 'Call',
    bet: 'Bet',
    raiseTo: 'Raise to',
    allin: 'All-in',
    min: 'Min',
    half: '½ pot',
    threeq: '¾ pot',
    potBtn: 'Pot',
    max: 'All-in',
    yourTurn: 'Your turn',
    waiting: 'Waiting for {name}',
    wins: '{name} wins {amount}',
    youWin: 'You win {amount}',
    split: 'Split pot',
    out: 'Out',
    folded: 'Folded',
    keys: 'F fold · C check/call · R raise · A all-in',
    actions: { check: 'Check', call: 'Call', bet: 'Bet', raise: 'Raise', fold: 'Fold', allin: 'All-in', sb: 'SB', bb: 'BB' } as Record<string, string>,
    streets: { preflop: 'Pre-flop', flop: 'Flop', turn: 'Turn', river: 'River', showdown: 'Showdown', over: 'Hand over' } as Record<string, string>,
  },
  board: {
    cancel: 'Esc to cancel',
    pickTarget: 'Pick a destination',
    yourMove: 'Your move',
  },
  card: {
    status: { lobby: 'Lobby', playing: 'Playing', finished: 'Finished', abandoned: 'Closed' } as Record<string, string>,
    open: 'Open table',
    loading: 'Loading table…',
    missing: 'Table unavailable',
  },
}

type Dict = typeof en

const zh: Dict = {
  lobby: {
    eyebrow: '游戏厅',
    title: '选一张桌子',
    sub: '和朋友、和智能体，或者一起玩。筹码永远是娱乐币。',
    featured: '精选',
    holdemName: '德州扑克',
    holdemSummary: '2 至 9 人无限注扑克。葵来发牌，每位智能体都有自己的打法。',
    playNow: '马上开玩',
    newTable: '开新桌',
    joinCode: '用邀请码加入',
    myGames: '我的游戏',
    community: '社区游戏',
    openTables: '开放的牌桌',
    myTables: '我的牌桌',
    noGames: '这里还是空的。在聊天里向葵描述一个游戏，智能体们会把它做出来。',
    noCommunity: '还没有社区游戏。',
    noTables: '目前没有牌桌。',
    seats: '座',
    plays: '局',
    by: '作者',
    open: '进入',
    join: '加入',
    loadError: '游戏厅加载失败，稍后自动重试。',
    retry: '重试',
    status: { building: '制作中', draft: '草稿', published: '已发布' },
  },
  newTable: {
    title: '开新桌',
    game: '游戏',
    name: '牌桌名称',
    namePh: '周五夜德州',
    seats: '座位',
    seatN: '{n} 号座',
    me: '我',
    agent: '智能体',
    open: '空座',
    openHint: '留给朋友',
    pickAgent: '选择智能体',
    options: '德州扑克设置',
    stack: '起始筹码',
    sb: '小盲',
    bb: '大盲',
    double: '盲注翻倍间隔',
    doubleUnit: '手（0 = 不翻倍）',
    maxHands: '最多手数',
    maxHandsHint: '0 = 直到一人赢走全部筹码',
    clock: '行动计时',
    noClock: '不计时',
    create: '创建牌桌',
    creating: '创建中…',
    cancel: '取消',
    tight: '紧度',
    aggr: '激进',
    bluff: '诈唬',
    talk: '健谈',
  },
  join: {
    title: '用邀请码加入',
    ph: 'ABC123',
    go: '加入',
    joining: '正在加入牌桌…',
    failed: '这个邀请码无效。',
    back: '返回游戏厅',
  },
  detail: {
    rules: '规则',
    versions: '版本',
    playtest: '试玩测试',
    play: '开玩',
    seats: '{min}–{max} 人',
    hidden: '隐藏信息',
    perfect: '完全信息',
    games: '局',
    avgTurns: '平均回合',
    seatWins: '各座胜率',
    noRules: '规则尚未写好。',
    back: '全部游戏',
  },
  room: {
    loading: '正在入座…',
    notFound: '找不到这张牌桌。',
    back: '游戏厅',
    leave: '离开',
    leaveConfirm: '确定离开？你的座位将由智能体接手。',
    leaveYes: '离开牌桌',
    stay: '留下',
    spectating: '观战中',
    reconnecting: '重新连接中…',
    offline: '已离线，正在重试…',
    live: '实时',
    lobbyTitle: '等待玩家',
    invite: '邀请码',
    copyLink: '复制邀请链接',
    copied: '已复制',
    start: '开始游戏',
    starting: '开始中…',
    waitHost: '等待房主开始。',
    openSeat: '空座',
    makeOpen: '设为空座',
    makeAgent: '请智能体入座',
    host: '房主',
    you: '你',
    finished: '游戏结束',
    rematch: '再来一局',
    backToLobby: '返回游戏厅',
    abandoned: '这张牌桌已关闭。',
    chat: '聊天',
    log: '记录',
    players: '玩家',
    say: '说点什么…',
    send: '发送',
    noChat: '还没有消息，打个招呼吧。',
    noLog: '还没有发生任何事。',
    agentBadge: 'AI',
    panel: '牌桌聊天',
    close: '关闭',
    moveFailed: '操作被拒绝',
    stale: '牌局已更新，这是最新状态。',
    rank: ['冠军', '亚军', '季军', '第 4', '第 5', '第 6', '第 7', '第 8', '第 9'],
    score: '得分',
    tapVoice: '点一下，听葵说话',
  },
  holdem: {
    pot: '底池',
    side: '边池',
    hand: '第 {n} 手',
    handsLeft: '剩 {n} 手',
    blinds: '盲注 {sb}/{bb}',
    fold: '弃牌',
    check: '过牌',
    call: '跟注',
    bet: '下注',
    raiseTo: '加注到',
    allin: '全下',
    min: '最小',
    half: '½ 池',
    threeq: '¾ 池',
    potBtn: '满池',
    max: '全下',
    yourTurn: '轮到你了',
    waiting: '等待 {name}',
    wins: '{name} 赢得 {amount}',
    youWin: '你赢得 {amount}',
    split: '平分底池',
    out: '出局',
    folded: '已弃牌',
    keys: 'F 弃牌 · C 过牌/跟注 · R 加注 · A 全下',
    actions: { check: '过牌', call: '跟注', bet: '下注', raise: '加注', fold: '弃牌', allin: '全下', sb: '小盲', bb: '大盲' },
    streets: { preflop: '翻牌前', flop: '翻牌', turn: '转牌', river: '河牌', showdown: '摊牌', over: '本手结束' },
  },
  board: {
    cancel: '按 Esc 取消',
    pickTarget: '选择目标格',
    yourMove: '轮到你',
  },
  card: {
    status: { lobby: '等待中', playing: '进行中', finished: '已结束', abandoned: '已关闭' },
    open: '进入牌桌',
    loading: '正在加载牌桌…',
    missing: '牌桌不可用',
  },
}

export type PlayStrings = Dict

export function usePlayT() {
  const { lang } = useI18n()
  const s = lang === 'zh' ? zh : en
  const f = (str: string, vars: Record<string, string | number>) => str.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ''))
  return { s, f, lang }
}
