// Landing page copy, English and 中文. Written for players, not engineers:
// evenings with friends, a table that is always full, characters with real
// personalities, games you make by describing them, fairness, play money only.

const en = {
  meta: { title: "Play with Agents · A game table that is always full" },
  nav: {
    home: 'Play with Agents, home',
    links: [
      ['meet', 'Meet Aoi'],
      ['table', 'The table'],
      ['poker', "Hold'em"],
      ['build', 'Make a game'],
    ] as [string, string][],
    signin: 'Sign in',
    start: 'Get started',
    app: 'Open app',
    menu: 'Open menu',
    close: 'Close menu',
    menuTitle: 'Menu',
    toLight: 'Switch to light theme',
    toDark: 'Switch to dark theme',
  },
  hero: {
    tagline: ['A GAME TABLE THAT IS', 'ALWAYS FULL — EVEN AT 2 A.M.'],
    words: ['GAME', 'ON'],
    srTitle: 'Play with Agents: game on',
    pills: ['BLUFF', 'BUILD', 'WIN'],
    bottom: 'FRIENDS AND AI AGENTS — ONE TABLE, EVERY NIGHT',
    chips: ["Texas Hold'em", 'Make your own game', 'Play money only'],
    bubble: ["HI, I'M AOI, YOUR AI TEAMMATE.", 'DEAL YOU IN?'],
    bubbleCta: 'Take a seat',
    avatarAlt: 'Aoi',
  },
  card: {
    title: 'AOI · 葵',
    subtitle: 'AI AGENT PLAYER',
    kicker: 'NO. 001 · THE HOST',
    plate: 'DEAL ME IN',
    back: 'PLAY WITH AGENTS',
    backSub: 'THE TABLE IS ALWAYS FULL',
    caption: 'HOVER TO TILT · DRAG TO ROTATE · DOUBLE-CLICK TO FLIP',
    captionTouch: 'DRAG TO ROTATE · DOUBLE-TAP TO FLIP',
    label: 'Aoi’s holographic card. Drag to rotate; press Enter or double-click to flip it over.',
    portraitAlt: 'Aoi, the host, smiling',
  },
  meet: {
    eyebrow: 'Meet Aoi · 葵',
    title: ['Not just a player,', 'but your AI teammate.'],
    lead: 'Aoi hosts every table. She deals you in, explains the rules in plain words, plays to win — and teases you a little when you fold a good hand. Ask for a tip and she will teach you. Ask her to keep quiet and she will.',
    verbs: ['Hosts', 'Plays', 'Teases', 'Teaches'],
    traits: [
      ['Smart', 'Reads the table and remembers how you like to play.'],
      ['Friendly', 'Greets you by name and keeps the mood light.'],
      ['Competitive', 'She wants to win, and she will tell you so.'],
      ['Curious', 'Loves new games — and new people even more.'],
      ['Always learning', 'A little sharper every evening you play together.'],
    ] as [string, string][],
    fullAlt: 'Aoi, full body: long dark ponytail, glowing blue headset, black-and-blue jacket',
    profile: {
      title: 'Profile',
      rows: [
        ['Name', 'Aoi 葵'],
        ['Nationality', 'Japanese'],
        ['Role', 'Host · AI agent player'],
        ['Personality', 'Smart / Friendly / Competitive / Curious / Always learning'],
        ['Specialty', 'Reading the table · Teaching new players · Designing games'],
        ['Favorite', 'Games, challenges, new worlds'],
      ] as [string, string][],
      quote: '“Let’s do something amazing together.”',
    },
    faces: {
      title: 'Expressions',
      note: 'Every face you will see across the table.',
      items: [
        ['neutral', 'Neutral'],
        ['smile', 'Smile'],
        ['wink', 'Wink'],
        ['surprised', 'Surprised'],
        ['angry', 'Angry'],
        ['sad', 'Sad'],
      ] as [string, string][],
    },
    outfits: {
      title: 'Outfit variations',
      note: 'Tournament night, a lazy Sunday, summer games — she dresses for the occasion.',
      items: [
        ['default', 'Default'],
        ['casual', 'Casual'],
        ['combat', 'Combat'],
        ['summer', 'Summer'],
      ] as [string, string][],
    },
  },
  table: {
    eyebrow: 'The table is always full',
    title: ['Six characters.', 'Real personalities.', 'Always a seat.'],
    lead: 'Bring two friends or come alone. Every empty seat is taken by a character with a style of their own, so the game starts the moment you sit down.',
    plays: 'Plays',
    roster: [
      { id: 'aoi', name: 'Aoi', native: '葵', style: 'Balanced, adaptive', persona: 'The host. Warm, teasing and very competitive.' },
      { id: 'ren', name: 'Ren', native: '蓮', style: 'Tight & aggressive', persona: 'A calm strategist of few words and dry humour.' },
      { id: 'mika', name: 'Mika', native: '美香', style: 'Loose & aggressive', persona: 'A fearless showoff who lives for the all-in.' },
      { id: 'bram', name: 'Captain Bram', native: '', style: 'Calls a lot', persona: 'An old sailor who never folds a good story.' },
      { id: 'nova', name: 'Nova', native: '', style: 'Math-driven', persona: 'A cheerful robot who quotes the odds and tells terrible jokes.' },
      { id: 'lin', name: 'Lin', native: '琳', style: 'Tight, rarely bluffs', persona: 'A shy prodigy. Polite, and quietly deadly.' },
    ],
    invite: {
      title: 'Invite friends with a code',
      body: 'Open a table, share the code, and your friends join from any phone or laptop. The agents take whatever seats are left — and step aside when a friend arrives.',
      codeLabel: 'Table code',
      code: 'ACE-7Q2K',
      steps: ['Open a table', 'Share the code', 'Agents fill the rest'],
      you: 'You',
      friend: 'Friend',
      seatsAlt: 'Six seats around a table: you, two friends and three agents',
    },
  },
  poker: {
    eyebrow: 'Texas Hold’em tonight',
    title: ['Pull up a chair.', 'The cards are already moving.'],
    lead: 'Classic no-limit Hold’em, ready the moment you arrive. A quick hand before dinner, or a long tournament with friends that runs past midnight.',
    promises: [
      ['Play money only', 'Chips are just for fun. Nothing to buy, nothing to cash out — ever. No real-money gambling.'],
      ['Fair shuffles', 'Every deck is shuffled fairly, and every hand can be replayed afterwards.'],
      ['Your cards stay yours', 'The agents never see your cards. They read the table, just like you do.'],
      ['Tips while you learn', 'Ask Aoi what she would do. She explains why, then lets you decide.'],
      ['Turn clocks', 'A gentle timer keeps the game moving, so nobody is left waiting.'],
    ] as [string, string][],
    vignette: {
      label: 'An animated poker table: cards are dealt to you and five agents, chips slide into the pot.',
      pot: 'Pot',
      you: 'You',
      tip: 'Aoi: “Trips on this board? I’d raise.”',
      win: 'You win the pot!',
      actions: { raise: 'Raise', call: 'Call', fold: 'Fold', check: 'Check' },
    },
  },
  build: {
    eyebrow: 'Make your own game',
    title: ['Describe a game.', 'Play it tonight.'],
    lead: 'A game from your childhood, a twist on a classic, an idea you had in the shower — tell Aoi in your own words. Her studio team designs it, builds it, plays it hundreds of times to make sure it is fun and fair, and sets it on the table for tonight.',
    steps: [
      ['Describe it', '“A race across a river, but every stone sinks after you step on it.” One sentence is enough to start.'],
      ['The studio builds it', 'Aoi’s team writes the rules, draws the board and plays it hundreds of times, fixing anything unfair.'],
      ['Play it tonight', 'You give the final nod, and it is waiting at your table — for you, your friends and the agents.'],
    ] as [string, string][],
    chat: {
      title: 'Aoi’s game studio',
      status: 'Online',
      you: 'You',
      msgs: [
        ['you', 'Can we make a game where everyone is a fox stealing eggs — and the farmer is secretly one of us?'],
        ['aoi', 'A hidden farmer! I love it. Four to six players, foxes sneak each night, and one of you is quietly the farmer. Want a short timer on every night?'],
        ['you', 'Yes! And golden eggs should be worth more.'],
        ['aoi', 'Done. The team is building it now and will play it a few hundred times to keep it fair. I’ll call you when the table is set.'],
      ] as [string, string][],
      progressTitle: 'Fox & Farmer',
      progress: ['Rules written', 'Board drawn', 'Playtested 400 times', 'Ready for tonight'],
      input: 'Describe your game…',
    },
  },
  cta: {
    title: ['YOUR SEAT', 'IS WAITING'],
    body: 'Free to play. Play money only. Friends, agents, and a host who is very happy to see you.',
    button: 'Get started free',
    signin: 'I have an account',
    app: 'Open app',
  },
  footer: {
    terms: 'Terms',
    privacy: 'Privacy',
    family: 'A heros-agent.space family product',
    note: 'Play money only. No purchases, no cash-outs, no real-money gambling.',
    copy: '© 2026 Play with Agents',
  },
}

export type LandingStrings = typeof en

const zh: LandingStrings = {
  meta: { title: 'Play with Agents · 永远坐满的牌桌' },
  nav: {
    home: 'Play with Agents 首页',
    links: [
      ['meet', '认识葵'],
      ['table', '牌桌'],
      ['poker', '德州扑克'],
      ['build', '创造游戏'],
    ],
    signin: '登录',
    start: '开始游戏',
    app: '进入应用',
    menu: '打开菜单',
    close: '关闭菜单',
    menuTitle: '菜单',
    toLight: '切换到浅色主题',
    toDark: '切换到深色主题',
  },
  hero: {
    tagline: ['一张永远坐满的牌桌', '哪怕是凌晨两点'],
    words: ['一起', '玩'],
    srTitle: 'Play with Agents：一起玩',
    pills: ['诈唬', '创造', '赢下来'],
    bottom: '朋友与 AI 智能体 —— 同一张桌，每一个夜晚',
    chips: ['德州扑克', '创造你的游戏', '仅限娱乐筹码'],
    bubble: ['嗨，我是葵，你的 AI 队友。', '给你发牌吗？'],
    bubbleCta: '入座',
    avatarAlt: '葵',
  },
  card: {
    title: 'AOI · 葵',
    subtitle: 'AI AGENT PLAYER',
    kicker: 'NO. 001 · 主持人',
    plate: '发牌吧',
    back: 'PLAY WITH AGENTS',
    backSub: '永远坐满的牌桌',
    caption: '悬停倾斜 · 拖动旋转 · 双击翻面',
    captionTouch: '拖动旋转 · 双击翻面',
    label: '葵的全息卡牌。拖动可旋转，按回车或双击可翻面。',
    portraitAlt: '主持人葵在微笑',
  },
  meet: {
    eyebrow: '认识葵 · Aoi',
    title: ['不只是玩家，', '更是你的 AI 队友'],
    lead: '每一张桌都由葵来主持。她为你发牌，用大白话讲规则，认真想赢——你弃掉一手好牌时，她还会小小地调侃你一下。想要提示，她会耐心教你；想要安静，她就不出声。',
    verbs: ['主持', '对局', '调侃', '教学'],
    traits: [
      ['聪明', '看得懂牌局，也记得你喜欢怎么玩。'],
      ['友好', '叫得出你的名字，让气氛一直轻松。'],
      ['好胜', '她想赢，而且会直接告诉你。'],
      ['好奇', '热爱新游戏，更喜欢认识新朋友。'],
      ['不断学习', '每和你玩一晚，她都更厉害一点。'],
    ],
    fullAlt: '葵的全身像：黑色长马尾、发着蓝光的耳机、黑蓝相间的外套',
    profile: {
      title: '档案',
      rows: [
        ['名字', '葵 Aoi'],
        ['国籍', '日本'],
        ['身份', '主持人 · AI 智能体玩家'],
        ['性格', '聪明 / 友好 / 好胜 / 好奇 / 不断学习'],
        ['擅长', '读懂牌局 · 教新手 · 设计游戏'],
        ['喜欢', '游戏、挑战、新世界'],
      ],
      quote: '「一起，做更了不起的事吧。」',
    },
    faces: {
      title: '表情',
      note: '牌桌对面，你会看到的每一种表情。',
      items: [
        ['neutral', '平静'],
        ['smile', '微笑'],
        ['wink', '眨眼'],
        ['surprised', '惊讶'],
        ['angry', '生气'],
        ['sad', '难过'],
      ],
    },
    outfits: {
      title: '服装变化',
      note: '锦标赛之夜、慵懒的周日、夏日游戏——她总会换上合适的装扮。',
      items: [
        ['default', '默认'],
        ['casual', '休闲'],
        ['combat', '战斗'],
        ['summer', '夏日'],
      ],
    },
  },
  table: {
    eyebrow: '牌桌永远坐满',
    title: ['六位角色，', '真实的性格，', '永远有位子。'],
    lead: '约上两个朋友，或者一个人来。每个空位都会由一位风格鲜明的角色坐下——你一落座，牌局就开始。',
    plays: '打法',
    roster: [
      { id: 'aoi', name: '葵', native: 'Aoi', style: '均衡、善变通', persona: '主持人。温暖、爱调侃，而且非常好胜。' },
      { id: 'ren', name: '蓮', native: 'Ren', style: '紧凶', persona: '沉着的谋略家，话不多，冷幽默。' },
      { id: 'mika', name: '美香', native: 'Mika', style: '松凶、爱诈唬', persona: '无所畏惧的表演家，为全下而生。' },
      { id: 'bram', name: '布拉姆船长', native: 'Captain Bram', style: '爱跟注', persona: '老水手，讲故事从不弃牌。' },
      { id: 'nova', name: 'Nova', native: '诺娃', style: '数学派', persona: '开朗的机器人，张口就是胜率，还爱讲冷笑话。' },
      { id: 'lin', name: '琳', native: 'Lin', style: '紧弱、很少诈唬', persona: '害羞的天才少女。礼貌，却不声不响地致命。' },
    ],
    invite: {
      title: '用邀请码叫上朋友',
      body: '开一张桌，分享邀请码，朋友用手机或电脑就能加入。剩下的位子由智能体补上——朋友一到，它们就让座。',
      codeLabel: '牌桌邀请码',
      code: 'ACE-7Q2K',
      steps: ['开一张桌', '分享邀请码', '智能体补满空位'],
      you: '你',
      friend: '朋友',
      seatsAlt: '一张桌六个座位：你、两位朋友和三位智能体',
    },
  },
  poker: {
    eyebrow: '今晚，德州扑克',
    title: ['拉把椅子坐下，', '牌已经在发了。'],
    lead: '经典无限注德州扑克，一到就能开局。晚饭前打一手，或者和朋友来一场打到午夜之后的锦标赛。',
    promises: [
      ['仅限娱乐筹码', '筹码只为好玩。没有充值，没有兑现，永远不涉及真钱赌博。'],
      ['公平洗牌', '每副牌都公平洗过，每一手牌事后都能回放。'],
      ['你的底牌只属于你', '智能体永远看不到你的底牌。它们和你一样，只能读牌局。'],
      ['边玩边学', '问问葵她会怎么打。她会讲清楚原因，再让你自己决定。'],
      ['行动计时', '温和的计时器让牌局顺畅进行，没人需要干等。'],
    ],
    vignette: {
      label: '动态扑克桌：为你和五位智能体发牌，筹码滑入底池。',
      pot: '底池',
      you: '你',
      tip: '葵：「这个牌面你有三条？我会加注。」',
      win: '你赢下了底池！',
      actions: { raise: '加注', call: '跟注', fold: '弃牌', check: '过牌' },
    },
  },
  build: {
    eyebrow: '创造你自己的游戏',
    title: ['说出一个游戏，', '今晚就能玩。'],
    lead: '童年玩过的游戏、经典玩法的新花样、洗澡时冒出的点子——用你自己的话告诉葵。她的工作室团队会设计它、制作它、试玩上百次确保好玩又公平，然后把它摆上今晚的牌桌。',
    steps: [
      ['说出来', '「过河比赛，但每块石头踩过之后就会沉下去。」一句话就足够开始。'],
      ['工作室来制作', '葵的团队写规则、画棋盘，再试玩上百次，修掉一切不公平的地方。'],
      ['今晚就玩', '你点头确认，它就在你的牌桌上等着——等你、你的朋友和智能体们。'],
    ],
    chat: {
      title: '葵的游戏工作室',
      status: '在线',
      you: '你',
      msgs: [
        ['you', '能做一个游戏吗？大家都是偷蛋的狐狸——但农夫就藏在我们中间。'],
        ['aoi', '藏起来的农夫！我太喜欢了。四到六人，每晚狐狸们悄悄行动，其中一人其实是农夫。每一晚要加个短计时吗？'],
        ['you', '要！而且金蛋分数要更高。'],
        ['aoi', '没问题。团队正在制作，会先试玩几百次保证公平。牌桌摆好了我就叫你。'],
      ],
      progressTitle: '狐狸与农夫',
      progress: ['规则写好', '棋盘画好', '试玩 400 次', '今晚可玩'],
      input: '描述你的游戏…',
    },
  },
  cta: {
    title: ['你的座位', '已经备好'],
    body: '免费游玩，仅限娱乐筹码。朋友、智能体，还有一位很高兴见到你的主持人。',
    button: '免费开始',
    signin: '我已有账号',
    app: '进入应用',
  },
  footer: {
    terms: '服务条款',
    privacy: '隐私政策',
    family: 'heros-agent.space 家族产品',
    note: '仅限娱乐筹码。没有充值、没有兑现、没有真钱赌博。',
    copy: '© 2026 Play with Agents',
  },
}

export const landingStrings: Record<'en' | 'zh', LandingStrings> = { en, zh }
