// Landing page copy in English, 中文, 한국어 and 日本語. Written for players, not engineers:
// evenings with friends, a table that is always full, characters with real
// personalities, games you make by describing them, fairness, play money only.

const en = {
  meta: { title: "Play with Agents · A game table that is always full" },
  nav: {
    home: 'Play with Agents, home',
    links: [
      ['meet', 'Meet Aoi'],
      ['table', 'The table'],
      ['poker', "Hold'em"],
      ['build', 'Make a game'],
    ] as [string, string][],
    signin: 'Sign in',
    start: 'Get started',
    app: 'Open app',
    menu: 'Open menu',
    close: 'Close menu',
    menuTitle: 'Menu',
    toLight: 'Switch to light theme',
    toDark: 'Switch to dark theme',
  },
  hero: {
    tagline: ['A GAME TABLE THAT IS', 'ALWAYS FULL — EVEN AT 2 A.M.'],
    words: ['GAME', 'ON'],
    srTitle: 'Play with Agents: game on',
    pills: ['BLUFF', 'BUILD', 'WIN'],
    bottom: 'FRIENDS AND AI AGENTS — ONE TABLE, EVERY NIGHT',
    chips: ["Texas Hold'em", 'Make your own game', 'Play money only'],
    bubble: ["HI, I'M AOI, YOUR AI TEAMMATE.", 'DEAL YOU IN?'],
    bubbleCta: 'Take a seat',
    avatarAlt: 'Aoi',
  },
  card: {
    title: 'AOI · 葵',
    subtitle: 'AI AGENT PLAYER',
    kicker: 'NO. 001 · THE HOST',
    plate: 'DEAL ME IN',
    back: 'PLAY WITH AGENTS',
    backSub: 'THE TABLE IS ALWAYS FULL',
    caption: 'HOVER TO TILT · DRAG TO ROTATE · DOUBLE-CLICK TO FLIP',
    captionTouch: 'DRAG TO ROTATE · DOUBLE-TAP TO FLIP',
    label: 'Aoi’s holographic card. Drag to rotate; press Enter or double-click to flip it over.',
    portraitAlt: 'Aoi, the host, smiling',
  },
  meet: {
    eyebrow: 'Meet Aoi · 葵',
    title: ['Not just a player,', 'but your AI teammate.'],
    lead: 'Aoi hosts every table. She deals you in, explains the rules in plain words, plays to win — and teases you a little when you fold a good hand. Ask for a tip and she will teach you. Ask her to keep quiet and she will.',
    verbs: ['Hosts', 'Plays', 'Teases', 'Teaches'],
    traits: [
      ['Smart', 'Reads the table and remembers how you like to play.'],
      ['Friendly', 'Greets you by name and keeps the mood light.'],
      ['Competitive', 'She wants to win, and she will tell you so.'],
      ['Curious', 'Loves new games — and new people even more.'],
      ['Always learning', 'A little sharper every evening you play together.'],
    ] as [string, string][],
    fullAlt: 'Aoi, full body: long dark ponytail, glowing blue headset, black-and-blue jacket',
    profile: {
      title: 'Profile',
      rows: [
        ['Name', 'Aoi 葵'],
        ['Nationality', 'Japanese'],
        ['Role', 'Host · AI agent player'],
        ['Personality', 'Smart / Friendly / Competitive / Curious / Always learning'],
        ['Specialty', 'Reading the table · Teaching new players · Designing games'],
        ['Favorite', 'Games, challenges, new worlds'],
      ] as [string, string][],
      quote: '“Let’s do something amazing together.”',
    },
    faces: {
      title: 'Expressions',
      note: 'Every face you will see across the table.',
      items: [
        ['neutral', 'Neutral'],
        ['smile', 'Smile'],
        ['wink', 'Wink'],
        ['surprised', 'Surprised'],
        ['angry', 'Angry'],
        ['sad', 'Sad'],
      ] as [string, string][],
    },
    outfits: {
      title: 'Outfit variations',
      note: 'Tournament night, a lazy Sunday, summer games — she dresses for the occasion.',
      items: [
        ['default', 'Default'],
        ['casual', 'Casual'],
        ['combat', 'Combat'],
        ['summer', 'Summer'],
      ] as [string, string][],
    },
  },
  table: {
    eyebrow: 'The table is always full',
    title: ['Six characters.', 'Real personalities.', 'Always a seat.'],
    lead: 'Bring two friends or come alone. Every empty seat is taken by a character with a style of their own, so the game starts the moment you sit down.',
    plays: 'Plays',
    roster: [
      { id: 'aoi', name: 'Aoi', native: '葵', style: 'Balanced, adaptive', persona: 'The host. Warm, teasing and very competitive.' },
      { id: 'ren', name: 'Ren', native: '蓮', style: 'Tight & aggressive', persona: 'A calm strategist of few words and dry humour.' },
      { id: 'mika', name: 'Mika', native: '美香', style: 'Loose & aggressive', persona: 'A fearless showoff who lives for the all-in.' },
      { id: 'bram', name: 'Captain Bram', native: '', style: 'Calls a lot', persona: 'An old sailor who never folds a good story.' },
      { id: 'nova', name: 'Nova', native: '', style: 'Math-driven', persona: 'A cheerful robot who quotes the odds and tells terrible jokes.' },
      { id: 'lin', name: 'Lin', native: '琳', style: 'Tight, rarely bluffs', persona: 'A shy prodigy. Polite, and quietly deadly.' },
    ],
    invite: {
      title: 'Invite friends with a code',
      body: 'Open a table, share the code, and your friends join from any phone or laptop. The agents take whatever seats are left — and step aside when a friend arrives.',
      codeLabel: 'Table code',
      code: 'ACE-7Q2K',
      steps: ['Open a table', 'Share the code', 'Agents fill the rest'],
      you: 'You',
      friend: 'Friend',
      seatsAlt: 'Six seats around a table: you, two friends and three agents',
    },
  },
  poker: {
    eyebrow: 'Texas Hold’em tonight',
    title: ['Pull up a chair.', 'The cards are already moving.'],
    lead: 'Classic no-limit Hold’em, ready the moment you arrive. A quick hand before dinner, or a long tournament with friends that runs past midnight.',
    promises: [
      ['Play money only', 'Chips are just for fun. Nothing to buy, nothing to cash out — ever. No real-money gambling.'],
      ['Fair shuffles', 'Every deck is shuffled fairly, and every hand can be replayed afterwards.'],
      ['Your cards stay yours', 'The agents never see your cards. They read the table, just like you do.'],
      ['Tips while you learn', 'Ask Aoi what she would do. She explains why, then lets you decide.'],
      ['Turn clocks', 'A gentle timer keeps the game moving, so nobody is left waiting.'],
    ] as [string, string][],
    vignette: {
      label: 'An animated poker table: cards are dealt to you and five agents, chips slide into the pot.',
      pot: 'Pot',
      you: 'You',
      tip: 'Aoi: “Trips on this board? I’d raise.”',
      win: 'You win the pot!',
      actions: { raise: 'Raise', call: 'Call', fold: 'Fold', check: 'Check' },
    },
  },
  build: {
    eyebrow: 'Make your own game',
    title: ['Describe a game.', 'Play it tonight.'],
    lead: 'A game from your childhood, a twist on a classic, an idea you had in the shower — tell Aoi in your own words. Her studio team designs it, builds it, plays it hundreds of times to make sure it is fun and fair, and sets it on the table for tonight.',
    steps: [
      ['Describe it', '“A race across a river, but every stone sinks after you step on it.” One sentence is enough to start.'],
      ['The studio builds it', 'Aoi’s team writes the rules, draws the board and plays it hundreds of times, fixing anything unfair.'],
      ['Play it tonight', 'You give the final nod, and it is waiting at your table — for you, your friends and the agents.'],
    ] as [string, string][],
    chat: {
      title: 'Aoi’s game studio',
      status: 'Online',
      you: 'You',
      msgs: [
        ['you', 'Can we make a game where everyone is a fox stealing eggs — and the farmer is secretly one of us?'],
        ['aoi', 'A hidden farmer! I love it. Four to six players, foxes sneak each night, and one of you is quietly the farmer. Want a short timer on every night?'],
        ['you', 'Yes! And golden eggs should be worth more.'],
        ['aoi', 'Done. The team is building it now and will play it a few hundred times to keep it fair. I’ll call you when the table is set.'],
      ] as [string, string][],
      progressTitle: 'Fox & Farmer',
      progress: ['Rules written', 'Board drawn', 'Playtested 400 times', 'Ready for tonight'],
      input: 'Describe your game…',
    },
  },
  cta: {
    title: ['YOUR SEAT', 'IS WAITING'],
    body: 'Free to play. Play money only. Friends, agents, and a host who is very happy to see you.',
    button: 'Get started free',
    signin: 'I have an account',
    app: 'Open app',
  },
  footer: {
    terms: 'Terms',
    privacy: 'Privacy',
    family: 'A heros-agent.space family product',
    note: 'Play money only. No purchases, no cash-outs, no real-money gambling.',
    copy: '© 2026 Play with Agents',
  },
  a11y: { skip: 'Skip to content', primary: 'Primary', highlights: 'Highlights', verbs: 'What she does', footer: 'Footer' },
}

export type LandingStrings = typeof en

const zh: LandingStrings = {
  meta: { title: 'Play with Agents · 永远坐满的牌桌' },
  nav: {
    home: 'Play with Agents 首页',
    links: [
      ['meet', '认识葵'],
      ['table', '牌桌'],
      ['poker', '德州扑克'],
      ['build', '创造游戏'],
    ],
    signin: '登录',
    start: '开始游戏',
    app: '进入应用',
    menu: '打开菜单',
    close: '关闭菜单',
    menuTitle: '菜单',
    toLight: '切换到浅色主题',
    toDark: '切换到深色主题',
  },
  hero: {
    tagline: ['一张永远坐满的牌桌', '哪怕是凌晨两点'],
    words: ['一起', '玩'],
    srTitle: 'Play with Agents：一起玩',
    pills: ['诈唬', '创造', '赢下来'],
    bottom: '朋友与 AI 智能体 —— 同一张桌，每一个夜晚',
    chips: ['德州扑克', '创造你的游戏', '仅限娱乐筹码'],
    bubble: ['嗨，我是葵，你的 AI 队友。', '给你发牌吗？'],
    bubbleCta: '入座',
    avatarAlt: '葵',
  },
  card: {
    title: 'AOI · 葵',
    subtitle: 'AI AGENT PLAYER',
    kicker: 'NO. 001 · 主持人',
    plate: '发牌吧',
    back: 'PLAY WITH AGENTS',
    backSub: '永远坐满的牌桌',
    caption: '悬停倾斜 · 拖动旋转 · 双击翻面',
    captionTouch: '拖动旋转 · 双击翻面',
    label: '葵的全息卡牌。拖动可旋转，按回车或双击可翻面。',
    portraitAlt: '主持人葵在微笑',
  },
  meet: {
    eyebrow: '认识葵 · Aoi',
    title: ['不只是玩家，', '更是你的 AI 队友'],
    lead: '每一张桌都由葵来主持。她为你发牌，用大白话讲规则，认真想赢——你弃掉一手好牌时，她还会小小地调侃你一下。想要提示，她会耐心教你；想要安静，她就不出声。',
    verbs: ['主持', '对局', '调侃', '教学'],
    traits: [
      ['聪明', '看得懂牌局，也记得你喜欢怎么玩。'],
      ['友好', '叫得出你的名字，让气氛一直轻松。'],
      ['好胜', '她想赢，而且会直接告诉你。'],
      ['好奇', '热爱新游戏，更喜欢认识新朋友。'],
      ['不断学习', '每和你玩一晚，她都更厉害一点。'],
    ],
    fullAlt: '葵的全身像：黑色长马尾、发着蓝光的耳机、黑蓝相间的外套',
    profile: {
      title: '档案',
      rows: [
        ['名字', '葵 Aoi'],
        ['国籍', '日本'],
        ['身份', '主持人 · AI 智能体玩家'],
        ['性格', '聪明 / 友好 / 好胜 / 好奇 / 不断学习'],
        ['擅长', '读懂牌局 · 教新手 · 设计游戏'],
        ['喜欢', '游戏、挑战、新世界'],
      ],
      quote: '「一起，做更了不起的事吧。」',
    },
    faces: {
      title: '表情',
      note: '牌桌对面，你会看到的每一种表情。',
      items: [
        ['neutral', '平静'],
        ['smile', '微笑'],
        ['wink', '眨眼'],
        ['surprised', '惊讶'],
        ['angry', '生气'],
        ['sad', '难过'],
      ],
    },
    outfits: {
      title: '服装变化',
      note: '锦标赛之夜、慵懒的周日、夏日游戏——她总会换上合适的装扮。',
      items: [
        ['default', '默认'],
        ['casual', '休闲'],
        ['combat', '战斗'],
        ['summer', '夏日'],
      ],
    },
  },
  table: {
    eyebrow: '牌桌永远坐满',
    title: ['六位角色，', '真实的性格，', '永远有位子。'],
    lead: '约上两个朋友，或者一个人来。每个空位都会由一位风格鲜明的角色坐下——你一落座，牌局就开始。',
    plays: '打法',
    roster: [
      { id: 'aoi', name: '葵', native: 'Aoi', style: '均衡、善变通', persona: '主持人。温暖、爱调侃，而且非常好胜。' },
      { id: 'ren', name: '蓮', native: 'Ren', style: '紧凶', persona: '沉着的谋略家，话不多，冷幽默。' },
      { id: 'mika', name: '美香', native: 'Mika', style: '松凶、爱诈唬', persona: '无所畏惧的表演家，为全下而生。' },
      { id: 'bram', name: '布拉姆船长', native: 'Captain Bram', style: '爱跟注', persona: '老水手，讲故事从不弃牌。' },
      { id: 'nova', name: 'Nova', native: '诺娃', style: '数学派', persona: '开朗的机器人，张口就是胜率，还爱讲冷笑话。' },
      { id: 'lin', name: '琳', native: 'Lin', style: '紧弱、很少诈唬', persona: '害羞的天才少女。礼貌，却不声不响地致命。' },
    ],
    invite: {
      title: '用邀请码叫上朋友',
      body: '开一张桌，分享邀请码，朋友用手机或电脑就能加入。剩下的位子由智能体补上——朋友一到，它们就让座。',
      codeLabel: '牌桌邀请码',
      code: 'ACE-7Q2K',
      steps: ['开一张桌', '分享邀请码', '智能体补满空位'],
      you: '你',
      friend: '朋友',
      seatsAlt: '一张桌六个座位：你、两位朋友和三位智能体',
    },
  },
  poker: {
    eyebrow: '今晚，德州扑克',
    title: ['拉把椅子坐下，', '牌已经在发了。'],
    lead: '经典无限注德州扑克，一到就能开局。晚饭前打一手，或者和朋友来一场打到午夜之后的锦标赛。',
    promises: [
      ['仅限娱乐筹码', '筹码只为好玩。没有充值，没有兑现，永远不涉及真钱赌博。'],
      ['公平洗牌', '每副牌都公平洗过，每一手牌事后都能回放。'],
      ['你的底牌只属于你', '智能体永远看不到你的底牌。它们和你一样，只能读牌局。'],
      ['边玩边学', '问问葵她会怎么打。她会讲清楚原因，再让你自己决定。'],
      ['行动计时', '温和的计时器让牌局顺畅进行，没人需要干等。'],
    ],
    vignette: {
      label: '动态扑克桌：为你和五位智能体发牌，筹码滑入底池。',
      pot: '底池',
      you: '你',
      tip: '葵：「这个牌面你有三条？我会加注。」',
      win: '你赢下了底池！',
      actions: { raise: '加注', call: '跟注', fold: '弃牌', check: '过牌' },
    },
  },
  build: {
    eyebrow: '创造你自己的游戏',
    title: ['说出一个游戏，', '今晚就能玩。'],
    lead: '童年玩过的游戏、经典玩法的新花样、洗澡时冒出的点子——用你自己的话告诉葵。她的工作室团队会设计它、制作它、试玩上百次确保好玩又公平，然后把它摆上今晚的牌桌。',
    steps: [
      ['说出来', '「过河比赛，但每块石头踩过之后就会沉下去。」一句话就足够开始。'],
      ['工作室来制作', '葵的团队写规则、画棋盘，再试玩上百次，修掉一切不公平的地方。'],
      ['今晚就玩', '你点头确认，它就在你的牌桌上等着——等你、你的朋友和智能体们。'],
    ],
    chat: {
      title: '葵的游戏工作室',
      status: '在线',
      you: '你',
      msgs: [
        ['you', '能做一个游戏吗？大家都是偷蛋的狐狸——但农夫就藏在我们中间。'],
        ['aoi', '藏起来的农夫！我太喜欢了。四到六人，每晚狐狸们悄悄行动，其中一人其实是农夫。每一晚要加个短计时吗？'],
        ['you', '要！而且金蛋分数要更高。'],
        ['aoi', '没问题。团队正在制作，会先试玩几百次保证公平。牌桌摆好了我就叫你。'],
      ],
      progressTitle: '狐狸与农夫',
      progress: ['规则写好', '棋盘画好', '试玩 400 次', '今晚可玩'],
      input: '描述你的游戏…',
    },
  },
  cta: {
    title: ['你的座位', '已经备好'],
    body: '免费游玩，仅限娱乐筹码。朋友、智能体，还有一位很高兴见到你的主持人。',
    button: '免费开始',
    signin: '我已有账号',
    app: '进入应用',
  },
  footer: {
    terms: '服务条款',
    privacy: '隐私政策',
    family: 'heros-agent.space 家族产品',
    note: '仅限娱乐筹码。没有充值、没有兑现、没有真钱赌博。',
    copy: '© 2026 Play with Agents',
  },
  a11y: { skip: '跳到正文', primary: '主导航', highlights: '亮点', verbs: '她会做的事', footer: '页脚' },
}

const ko: LandingStrings = {
  meta: { title: 'Play with Agents · 언제나 꽉 찬 게임 테이블' },
  nav: {
    home: 'Play with Agents 홈',
    links: [
      ['meet', '아오이 소개'],
      ['table', '테이블'],
      ['poker', '홀덤'],
      ['build', '게임 만들기'],
    ],
    signin: '로그인',
    start: '시작하기',
    app: '앱 열기',
    menu: '메뉴 열기',
    close: '메뉴 닫기',
    menuTitle: '메뉴',
    toLight: '라이트 테마로 전환',
    toDark: '다크 테마로 전환',
  },
  hero: {
    tagline: ['언제 와도 꽉 찬 게임 테이블', '새벽 2시에도요'],
    words: ['한판', '붙자'],
    srTitle: 'Play with Agents: 한판 붙자',
    pills: ['블러프', '만들기', '승리'],
    bottom: '친구와 AI 에이전트 — 한 테이블에서, 매일 밤',
    chips: ['텍사스 홀덤', '나만의 게임 만들기', '게임 머니 전용'],
    bubble: ['안녕, 난 아오이! 너의 AI 팀메이트야.', '카드 돌려 줄까?'],
    bubbleCta: '자리에 앉기',
    avatarAlt: '아오이',
  },
  card: {
    title: 'AOI · 葵',
    subtitle: 'AI AGENT PLAYER',
    kicker: 'NO. 001 · 호스트',
    plate: '나도 낄래',
    back: 'PLAY WITH AGENTS',
    backSub: '언제나 꽉 찬 테이블',
    caption: '올리면 기울어요 · 드래그로 회전 · 더블클릭으로 뒤집기',
    captionTouch: '드래그로 회전 · 더블탭으로 뒤집기',
    label: '아오이의 홀로그램 카드. 드래그하면 회전하고, Enter 키나 더블클릭으로 뒤집을 수 있어요.',
    portraitAlt: '미소 짓는 호스트 아오이',
  },
  meet: {
    eyebrow: '아오이를 소개합니다 · 葵',
    title: ['플레이어 그 이상,', '당신의 AI 팀메이트.'],
    lead: '모든 테이블의 호스트는 아오이예요. 카드를 나눠 주고, 규칙은 쉬운 말로 설명해 주고, 이기려고 진심으로 플레이해요. 좋은 패를 폴드하면 살짝 놀리기도 하고요. 팁을 물으면 가르쳐 주고, 조용히 해 달라고 하면 조용히 있어요.',
    verbs: ['진행', '플레이', '장난', '코칭'],
    traits: [
      ['똑똑함', '테이블을 읽고, 당신이 좋아하는 플레이 스타일을 기억해요.'],
      ['다정함', '이름을 불러 반겨 주고, 분위기는 언제나 가볍게.'],
      ['승부욕', '이기고 싶어 해요. 그리고 대놓고 말해요.'],
      ['호기심', '새로운 게임이 좋아요. 새로운 사람은 더 좋고요.'],
      ['계속 성장', '함께 플레이하는 밤마다 조금씩 더 날카로워져요.'],
    ],
    fullAlt: '아오이 전신: 긴 검은 포니테일, 푸르게 빛나는 헤드셋, 검정과 파랑의 재킷',
    profile: {
      title: '프로필',
      rows: [
        ['이름', '아오이 葵'],
        ['국적', '일본'],
        ['역할', '호스트 · AI 에이전트 플레이어'],
        ['성격', '똑똑함 / 다정함 / 승부욕 / 호기심 / 계속 성장'],
        ['특기', '테이블 읽기 · 초보자 코칭 · 게임 디자인'],
        ['좋아하는 것', '게임, 도전, 새로운 세계'],
      ],
      quote: '“우리 같이, 끝내주는 거 해 보자.”',
    },
    faces: {
      title: '표정',
      note: '테이블 너머로 보게 될 모든 얼굴.',
      items: [
        ['neutral', '무표정'],
        ['smile', '미소'],
        ['wink', '윙크'],
        ['surprised', '놀람'],
        ['angry', '화남'],
        ['sad', '시무룩'],
      ],
    },
    outfits: {
      title: '의상 바리에이션',
      note: '토너먼트의 밤, 느긋한 일요일, 여름 게임 — 그날에 맞춰 옷을 갈아입어요.',
      items: [
        ['default', '기본'],
        ['casual', '캐주얼'],
        ['combat', '전투'],
        ['summer', '여름'],
      ],
    },
  },
  table: {
    eyebrow: '테이블은 언제나 만석',
    title: ['여섯 캐릭터.', '진짜 개성.', '언제나 당신 자리.'],
    lead: '친구 둘을 데려와도, 혼자 와도 좋아요. 빈자리마다 저마다의 스타일을 가진 캐릭터가 앉으니까, 당신이 앉는 순간 게임이 시작돼요.',
    plays: '스타일',
    roster: [
      { id: 'aoi', name: '아오이', native: '葵', style: '밸런스형, 유연함', persona: '호스트. 다정하고, 장난기 많고, 승부욕이 엄청나요.' },
      { id: 'ren', name: '렌', native: '蓮', style: '타이트 & 어그레시브', persona: '말수 적은 냉철한 전략가. 유머는 건조하게.' },
      { id: 'mika', name: '미카', native: '美香', style: '루스 & 어그레시브', persona: '겁 없는 무대 체질. 올인이 인생의 낙이에요.' },
      { id: 'bram', name: '브램 선장', native: 'Captain Bram', style: '콜을 자주 함', persona: '늙은 뱃사람. 좋은 이야기 앞에선 절대 폴드하지 않아요.' },
      { id: 'nova', name: '노바', native: 'Nova', style: '확률 중심', persona: '확률을 줄줄 읊고 썰렁한 농담을 던지는 명랑한 로봇.' },
      { id: 'lin', name: '린', native: '琳', style: '타이트, 블러프는 드물게', persona: '수줍은 천재 소녀. 예의 바르고, 조용히 치명적이에요.' },
    ],
    invite: {
      title: '코드로 친구 초대',
      body: '테이블을 열고 코드를 공유하면, 친구는 휴대폰이든 노트북이든 바로 들어와요. 남은 자리는 에이전트가 채우고, 친구가 오면 자리를 비켜 줘요.',
      codeLabel: '테이블 코드',
      code: 'ACE-7Q2K',
      steps: ['테이블 열기', '코드 공유', '나머지는 에이전트가'],
      you: '나',
      friend: '친구',
      seatsAlt: '테이블을 둘러싼 여섯 자리: 나, 친구 둘, 에이전트 셋',
    },
  },
  poker: {
    eyebrow: '오늘 밤은 텍사스 홀덤',
    title: ['어서 앉아요.', '카드는 벌써 돌아요.'],
    lead: '정통 노리밋 홀덤, 오자마자 바로 시작. 저녁 먹기 전에 가볍게 한 판, 아니면 친구들과 자정 넘어서까지 토너먼트.',
    promises: [
      ['게임 머니 전용', '칩은 오직 재미를 위한 것. 살 수도, 현금으로 바꿀 수도 없어요. 실제 돈이 걸린 도박은 절대 없어요.'],
      ['공정한 셔플', '모든 덱은 공정하게 섞이고, 모든 핸드는 나중에 다시 볼 수 있어요.'],
      ['내 카드는 나만', '에이전트는 절대 당신의 카드를 보지 못해요. 당신처럼 테이블을 읽을 뿐이에요.'],
      ['배우면서 플레이', '아오이에게 어떻게 할지 물어보세요. 이유를 알려 주고, 결정은 당신에게 맡겨요.'],
      ['턴 타이머', '부드러운 타이머로 게임은 술술. 아무도 하염없이 기다리지 않아요.'],
    ],
    vignette: {
      label: '애니메이션 포커 테이블: 당신과 다섯 에이전트에게 카드가 돌고, 칩이 팟으로 미끄러져 들어가요.',
      pot: '팟',
      you: '나',
      tip: '아오이: “이 보드에서 트리플? 나라면 레이즈.”',
      win: '팟은 당신 거예요!',
      actions: { raise: '레이즈', call: '콜', fold: '폴드', check: '체크' },
    },
  },
  build: {
    eyebrow: '나만의 게임 만들기',
    title: ['말로 설명하면,', '오늘 밤 플레이.'],
    lead: '어릴 적 하던 게임, 클래식의 새로운 변주, 샤워하다 떠오른 아이디어 — 당신의 말로 아오이에게 들려주세요. 아오이의 스튜디오 팀이 디자인하고, 만들고, 수백 번 플레이하며 재밌고 공정한지 확인한 다음 오늘 밤 테이블에 올려 둬요.',
    steps: [
      ['말해 보기', '“강을 건너는 레이스인데, 밟은 돌은 전부 가라앉아.” 시작은 한 문장이면 충분해요.'],
      ['스튜디오가 제작', '아오이의 팀이 규칙을 쓰고, 보드를 그리고, 수백 번 플레이하며 불공정한 부분을 고쳐요.'],
      ['오늘 밤 플레이', '당신이 OK 하면 테이블에서 기다리고 있어요 — 당신과 친구들, 그리고 에이전트들을.'],
    ],
    chat: {
      title: '아오이의 게임 스튜디오',
      status: '온라인',
      you: '나',
      msgs: [
        ['you', '다들 달걀 훔치는 여우인데, 농부가 몰래 우리 중에 숨어 있는 게임 만들 수 있어?'],
        ['aoi', '숨은 농부라니! 완전 좋아. 4~6명이 하고, 여우들은 밤마다 몰래 움직이고, 그중 한 명이 사실 농부야. 밤마다 짧은 타이머도 넣을까?'],
        ['you', '응! 그리고 황금 달걀은 점수가 더 높았으면 좋겠어.'],
        ['aoi', '오케이. 팀이 지금 만들고 있고, 공정하도록 몇백 번 플레이해 볼게. 테이블 준비되면 부를게!'],
      ],
      progressTitle: '여우와 농부',
      progress: ['규칙 완성', '보드 완성', '400번 플레이테스트', '오늘 밤 플레이 가능'],
      input: '당신의 게임을 설명해 주세요…',
    },
  },
  cta: {
    title: ['네 자리', '맡아 놨어'],
    body: '무료 플레이, 게임 머니 전용. 친구들, 에이전트들, 그리고 당신을 정말 반가워할 호스트가 기다려요.',
    button: '무료로 시작하기',
    signin: '이미 계정이 있어요',
    app: '앱 열기',
  },
  footer: {
    terms: '이용약관',
    privacy: '개인정보처리방침',
    family: 'heros-agent.space 패밀리 서비스',
    note: '게임 머니 전용. 구매, 현금화, 실제 돈 도박은 일절 없어요.',
    copy: '© 2026 Play with Agents',
  },
  a11y: { skip: '본문으로 건너뛰기', primary: '주 메뉴', highlights: '하이라이트', verbs: '아오이가 하는 일', footer: '푸터' },
}

const ja: LandingStrings = {
  meta: { title: 'Play with Agents · いつでも満席のゲームテーブル' },
  nav: {
    home: 'Play with Agents ホーム',
    links: [
      ['meet', '葵に会う'],
      ['table', 'テーブル'],
      ['poker', 'ホールデム'],
      ['build', 'ゲームづくり'],
    ],
    signin: 'ログイン',
    start: 'はじめる',
    app: 'アプリを開く',
    menu: 'メニューを開く',
    close: 'メニューを閉じる',
    menuTitle: 'メニュー',
    toLight: 'ライトテーマに切り替え',
    toDark: 'ダークテーマに切り替え',
  },
  hero: {
    tagline: ['いつ来ても満席のゲームテーブル', '深夜2時だって'],
    words: ['いざ', '勝負'],
    srTitle: 'Play with Agents：いざ、勝負',
    pills: ['ブラフ', 'つくる', '勝つ'],
    bottom: '友だちとAIエージェント — 同じテーブルで、毎晩',
    chips: ['テキサスホールデム', 'ゲームを自作', 'プレイマネーのみ'],
    bubble: ['やあ、AIチームメイトの葵（アオイ）だよ。', 'ひと勝負、どう？'],
    bubbleCta: '席につく',
    avatarAlt: '葵',
  },
  card: {
    title: 'AOI · 葵',
    subtitle: 'AI AGENT PLAYER',
    kicker: 'NO. 001 · ホスト',
    plate: '配って！',
    back: 'PLAY WITH AGENTS',
    backSub: 'いつでも満席のテーブル',
    caption: 'ホバーで傾く · ドラッグで回転 · ダブルクリックで裏返す',
    captionTouch: 'ドラッグで回転 · ダブルタップで裏返す',
    label: '葵のホログラムカード。ドラッグで回転、Enterキーかダブルクリックで裏返せます。',
    portraitAlt: 'ほほえむホストの葵',
  },
  meet: {
    eyebrow: 'はじめまして · 葵（アオイ）',
    title: ['ただのプレイヤーじゃない。', 'キミのAIチームメイト。'],
    lead: 'どのテーブルも、ホストは葵。カードを配って、ルールはやさしい言葉で説明して、本気で勝ちにいく。いい手をフォールドしたら、ちょっぴりからかってくることも。コツを聞けば教えてくれるし、静かにしてと言えばちゃんと黙ります。',
    verbs: ['もてなす', '戦う', 'からかう', '教える'],
    traits: [
      ['賢い', 'テーブルを読み、あなたの好きな打ち方も覚えている。'],
      ['フレンドリー', '名前を呼んで迎えてくれて、場の空気はいつも軽やか。'],
      ['負けず嫌い', '勝ちたい。そして、それを隠さない。'],
      ['好奇心旺盛', '新しいゲームが大好き。新しい人は、もっと好き。'],
      ['成長し続ける', '一緒に遊ぶ夜ごとに、少しずつ手強くなる。'],
    ],
    fullAlt: '葵の全身：黒髪のロングポニーテール、青く光るヘッドセット、黒と青のジャケット',
    profile: {
      title: 'プロフィール',
      rows: [
        ['名前', '葵（アオイ）Aoi'],
        ['国籍', '日本'],
        ['役割', 'ホスト · AIエージェントプレイヤー'],
        ['性格', '賢い / フレンドリー / 負けず嫌い / 好奇心旺盛 / 成長し続ける'],
        ['得意', 'テーブルを読む · 初心者へのレクチャー · ゲームづくり'],
        ['好きなもの', 'ゲーム、挑戦、新しい世界'],
      ],
      quote: '「一緒に、すごいことしようよ。」',
    },
    faces: {
      title: '表情',
      note: 'テーブル越しに見せる、いろんな顔。',
      items: [
        ['neutral', 'ふつう'],
        ['smile', '笑顔'],
        ['wink', 'ウインク'],
        ['surprised', 'びっくり'],
        ['angry', 'むっ'],
        ['sad', 'しょんぼり'],
      ],
    },
    outfits: {
      title: '衣装バリエーション',
      note: 'トーナメントの夜、のんびり日曜、夏のゲーム — その日に合わせて着替えます。',
      items: [
        ['default', 'デフォルト'],
        ['casual', 'カジュアル'],
        ['combat', 'バトル'],
        ['summer', 'サマー'],
      ],
    },
  },
  table: {
    eyebrow: 'テーブルはいつも満席',
    title: ['6人のキャラクター。', 'ホンモノの個性。', '席は、いつでも。'],
    lead: '友だち2人を誘っても、ひとりで来てもOK。空いた席には個性豊かなキャラクターが座るから、あなたが座った瞬間にゲームが始まります。',
    plays: 'スタイル',
    roster: [
      { id: 'aoi', name: '葵', native: 'アオイ', style: 'バランス型・柔軟', persona: 'ホスト。あたたかくて、からかい好きで、大の負けず嫌い。' },
      { id: 'ren', name: 'レン', native: '蓮', style: 'タイト＆アグレッシブ', persona: '口数少なめの冷静な策士。ユーモアはドライ。' },
      { id: 'mika', name: 'ミカ', native: '美香', style: 'ルース＆アグレッシブ', persona: '怖いもの知らずの目立ちたがり。オールインこそ生きがい。' },
      { id: 'bram', name: 'ブラム船長', native: 'Captain Bram', style: 'コール多め', persona: '年季の入った船乗り。いい話からは決して降りない。' },
      { id: 'nova', name: 'ノヴァ', native: 'Nova', style: '確率重視', persona: '陽気なロボット。オッズをそらんじ、ひどいジョークを飛ばす。' },
      { id: 'lin', name: 'リン', native: '琳', style: 'タイト・ブラフはまれ', persona: '内気な天才少女。礼儀正しく、静かに致命的。' },
    ],
    invite: {
      title: 'コードで友だちを招待',
      body: 'テーブルを開いてコードを送るだけ。友だちはスマホからでもPCからでも参加できます。残りの席はエージェントが埋めて、友だちが来たらさっと席を譲ります。',
      codeLabel: 'テーブルコード',
      code: 'ACE-7Q2K',
      steps: ['テーブルを開く', 'コードを送る', '残りはエージェントが'],
      you: 'あなた',
      friend: '友だち',
      seatsAlt: 'テーブルを囲む6つの席：あなた、友だち2人、エージェント3人',
    },
  },
  poker: {
    eyebrow: '今夜はテキサスホールデム',
    title: ['さあ、座って。', 'カードはもう配られてる。'],
    lead: '定番のノーリミット・ホールデムが、来たその瞬間から遊べます。夕食前にサクッと1ハンド。友だちと真夜中過ぎまでトーナメント。',
    promises: [
      ['プレイマネーのみ', 'チップは遊びのためだけのもの。購入も換金も一切なし。リアルマネーのギャンブルではありません。'],
      ['公平なシャッフル', 'すべてのデッキを公平にシャッフル。どのハンドも、あとからリプレイできます。'],
      ['あなたの手札は、あなただけ', 'エージェントがあなたのカードを見ることはありません。あなたと同じように、テーブルを読むだけ。'],
      ['遊びながら上達', '「葵ならどうする？」と聞いてみて。理由を説明したうえで、決めるのはあなたです。'],
      ['ターンタイマー', 'やさしいタイマーでゲームはテンポよく。誰も待たされません。'],
    ],
    vignette: {
      label: 'アニメーションのポーカーテーブル：あなたと5人のエージェントにカードが配られ、チップがポットへ滑り込む。',
      pot: 'ポット',
      you: 'あなた',
      tip: '葵：「このボードでスリーカード？ 私ならレイズかな。」',
      win: 'ポット獲得！',
      actions: { raise: 'レイズ', call: 'コール', fold: 'フォールド', check: 'チェック' },
    },
  },
  build: {
    eyebrow: 'ゲームをつくろう',
    title: ['話すだけで、', '今夜遊べる。'],
    lead: '子どもの頃に遊んだゲーム、定番のアレンジ、シャワー中のひらめき — 自分の言葉で葵に話してみて。葵のスタジオチームがデザインして、作って、何百回もテストプレイ。楽しくて公平なことを確かめてから、今夜のテーブルに並べます。',
    steps: [
      ['話してみる', '「川を渡るレース。でも踏んだ石は沈んでいく。」最初はひと言で十分。'],
      ['スタジオが作る', '葵のチームがルールを書き、ボードを描き、何百回も遊んで不公平なところを直します。'],
      ['今夜プレイ', 'あなたがOKを出せば、テーブルで待っています。あなたと友だち、そしてエージェントたちを。'],
    ],
    chat: {
      title: '葵のゲームスタジオ',
      status: 'オンライン',
      you: 'あなた',
      msgs: [
        ['you', 'みんなが卵を盗むキツネになるゲームって作れる？ しかも農家がこっそり私たちの中にいるの。'],
        ['aoi', '隠れ農家！ それ最高。4〜6人で、キツネは毎晩こっそり動いて、誰かひとりが実は農家。夜ごとに短いタイマーもつける？'],
        ['you', 'つける！ あと金の卵は高得点にしたい。'],
        ['aoi', 'りょうかい。チームがいま作ってて、公平になるよう数百回テストプレイするね。テーブルの準備ができたら呼ぶよ。'],
      ],
      progressTitle: 'キツネと農家',
      progress: ['ルール完成', 'ボード完成', 'テストプレイ400回', '今夜プレイ可能'],
      input: 'あなたのゲームを話してみて…',
    },
  },
  cta: {
    title: ['キミの席', 'とってある'],
    body: '無料で遊べて、プレイマネーのみ。友だち、エージェント、そしてあなたに会えるのを楽しみにしているホストが待っています。',
    button: '無料ではじめる',
    signin: 'アカウントをお持ちの方',
    app: 'アプリを開く',
  },
  footer: {
    terms: '利用規約',
    privacy: 'プライバシー',
    family: 'heros-agent.space ファミリーのサービス',
    note: 'プレイマネーのみ。購入・換金・リアルマネーのギャンブルは一切ありません。',
    copy: '© 2026 Play with Agents',
  },
  a11y: { skip: '本文へスキップ', primary: 'メインナビゲーション', highlights: 'ハイライト', verbs: '葵がすること', footer: 'フッター' },
}

export const landingStrings: Record<'en' | 'zh' | 'ko' | 'ja', LandingStrings> = { en, zh, ko, ja }
