// Package art makes game covers: 16:9 illustrations generated by an
// image model (Alibaba DashScope, the wan text-to-image models), re-encoded
// small enough to keep in Postgres, and a deterministic procedural cover for
// when there is no key or the model fails. A build never fails because of
// art: every path ends in an image.
package art

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// Defaults for the DashScope text-to-image task API.
const (
	DefaultBaseURL       = "https://dashscope.aliyuncs.com/api/v1"
	DefaultModel         = "wan2.5-t2i-preview"
	DefaultFallbackModel = "wan2.2-t2i-flash"
	// Size is what the model is asked for and what covers are stored at.
	Width, Height = 1280, 720
	// MaxAttempts bounds image calls per cover: the primary model, then the
	// fallback model once.
	MaxAttempts = 2
	// CostPerImageUSD is a conservative estimate per generated image, added
	// to the goal's cost so covers count against the build's budget.
	CostPerImageUSD = 0.04
)

// Client calls the DashScope async image-synthesis API. The zero value is
// unusable; NewClient fills the defaults. A Client without a key is
// disabled (Enabled false) and callers use the procedural cover.
type Client struct {
	APIKey        string
	Model         string
	FallbackModel string
	BaseURL       string
	HTTP          *http.Client
	// PollEvery is the wait between task polls; PollFor bounds the whole
	// wait for one task (about 3 minutes).
	PollEvery time.Duration
	PollFor   time.Duration
}

// NewClient returns a client for key (may be empty: disabled) and model
// (empty: DefaultModel).
func NewClient(key, model string) *Client {
	if model == "" {
		model = DefaultModel
	}
	fb := DefaultFallbackModel
	if fb == model {
		fb = ""
	}
	return &Client{APIKey: strings.TrimSpace(key), Model: model, FallbackModel: fb, BaseURL: DefaultBaseURL,
		HTTP: &http.Client{Timeout: 60 * time.Second}, PollEvery: 5 * time.Second, PollFor: 3 * time.Minute}
}

// Enabled reports whether the client can generate images at all.
func (c *Client) Enabled() bool { return c != nil && c.APIKey != "" }

// Models is the order generation tries, at most MaxAttempts long.
func (c *Client) Models() []string {
	out := []string{c.Model}
	if c.FallbackModel != "" && c.FallbackModel != c.Model {
		out = append(out, c.FallbackModel)
	}
	if len(out) > MaxAttempts {
		out = out[:MaxAttempts]
	}
	return out
}

// ErrDisabled is returned by Generate on a client without a key.
var ErrDisabled = errors.New("image generation is not configured")

// Generate runs one text-to-image task with model and returns the first
// image's raw bytes as downloaded. It submits, polls (bounded by PollFor)
// and downloads; any failure is an error and nothing is retried here.
func (c *Client) Generate(ctx context.Context, model, prompt, negative string) ([]byte, error) {
	if !c.Enabled() {
		return nil, ErrDisabled
	}
	body, _ := json.Marshal(map[string]any{
		"model": model,
		"input": map[string]any{"prompt": prompt, "negative_prompt": negative},
		"parameters": map[string]any{"size": fmt.Sprintf("%d*%d", Width, Height), "n": 1,
			"prompt_extend": false, "watermark": false},
	})
	var sub struct {
		Output struct {
			TaskID     string `json:"task_id"`
			TaskStatus string `json:"task_status"`
		} `json:"output"`
		Code    string `json:"code"`
		Message string `json:"message"`
	}
	if err := c.do(ctx, http.MethodPost, c.base()+"/services/aigc/text2image/image-synthesis", body, true, &sub); err != nil {
		return nil, fmt.Errorf("submit: %w", err)
	}
	if sub.Output.TaskID == "" {
		return nil, fmt.Errorf("submit: no task id (%s %s)", sub.Code, clip(sub.Message, 200))
	}
	url, err := c.poll(ctx, sub.Output.TaskID)
	if err != nil {
		return nil, err
	}
	return c.download(ctx, url)
}

func (c *Client) base() string {
	if c.BaseURL == "" {
		return DefaultBaseURL
	}
	return strings.TrimRight(c.BaseURL, "/")
}

// poll waits for the task, bounded by PollFor (and ctx).
func (c *Client) poll(ctx context.Context, taskID string) (string, error) {
	every, limit := c.PollEvery, c.PollFor
	if every <= 0 {
		every = 5 * time.Second
	}
	if limit <= 0 {
		limit = 3 * time.Minute
	}
	maxPolls := int(limit/every) + 1
	for i := 0; i < maxPolls; i++ {
		if i > 0 {
			select {
			case <-ctx.Done():
				return "", ctx.Err()
			case <-time.After(every):
			}
		}
		var st struct {
			Output struct {
				TaskStatus string `json:"task_status"`
				Code       string `json:"code"`
				Message    string `json:"message"`
				Results    []struct {
					URL     string `json:"url"`
					Code    string `json:"code"`
					Message string `json:"message"`
				} `json:"results"`
			} `json:"output"`
		}
		if err := c.do(ctx, http.MethodGet, c.base()+"/tasks/"+taskID, nil, false, &st); err != nil {
			// One flaky poll is not the end of the task.
			if ctx.Err() != nil {
				return "", ctx.Err()
			}
			continue
		}
		switch st.Output.TaskStatus {
		case "SUCCEEDED":
			for _, r := range st.Output.Results {
				if r.URL != "" {
					return r.URL, nil
				}
			}
			msg := ""
			if len(st.Output.Results) > 0 {
				msg = st.Output.Results[0].Code + " " + st.Output.Results[0].Message
			}
			return "", fmt.Errorf("task %s succeeded without an image (%s)", taskID, clip(msg, 200))
		case "FAILED", "CANCELED", "UNKNOWN":
			return "", fmt.Errorf("task %s %s: %s %s", taskID, st.Output.TaskStatus, st.Output.Code, clip(st.Output.Message, 200))
		}
	}
	return "", fmt.Errorf("task %s did not finish within %s", taskID, limit)
}

func (c *Client) download(ctx context.Context, url string) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	resp, err := c.httpClient().Do(req)
	if err != nil {
		return nil, fmt.Errorf("download: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("download: status %d", resp.StatusCode)
	}
	b, err := io.ReadAll(io.LimitReader(resp.Body, 20<<20))
	if err != nil {
		return nil, fmt.Errorf("download: %w", err)
	}
	return b, nil
}

func (c *Client) httpClient() *http.Client {
	if c.HTTP != nil {
		return c.HTTP
	}
	return http.DefaultClient
}

// do sends one API request. The key travels only in the Authorization
// header and never appears in an error.
func (c *Client) do(ctx context.Context, method, url string, body []byte, async bool, out any) error {
	var rd io.Reader
	if body != nil {
		rd = bytes.NewReader(body)
	}
	req, err := http.NewRequestWithContext(ctx, method, url, rd)
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+c.APIKey)
	req.Header.Set("Content-Type", "application/json")
	if async {
		req.Header.Set("X-DashScope-Async", "enable")
	}
	resp, err := c.httpClient().Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if resp.StatusCode/100 != 2 {
		var e struct{ Code, Message string }
		_ = json.Unmarshal(raw, &e)
		return fmt.Errorf("status %d: %s %s", resp.StatusCode, e.Code, clip(e.Message, 200))
	}
	return json.Unmarshal(raw, out)
}

func clip(s string, n int) string {
	r := []rune(strings.TrimSpace(s))
	if len(r) <= n {
		return string(r)
	}
	return string(r[:n]) + "…"
}
