package holdem

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"math/rand"
	"os"
	"testing"
)

// TestGeneratePreflopTable regenerates preflop_table.go: the heads-up equity
// of every one of the 169 starting-hand classes against a random hand. It
// only runs on request, because it takes a few seconds and its output is
// committed:
//
//	HOLDEM_GEN_PREFLOP=1 go test ./internal/games/holdem -run TestGeneratePreflopTable
func TestGeneratePreflopTable(t *testing.T) {
	if os.Getenv("HOLDEM_GEN_PREFLOP") != "1" {
		t.Skip("set HOLDEM_GEN_PREFLOP=1 to regenerate preflop_table.go")
	}
	const sims = 100_000
	rng := rand.New(rand.NewSource(20261002))
	var tab [13][13]float64
	for r := 0; r < 13; r++ {
		for c := 0; c < 13; c++ {
			// Representative cards for the class at (r,c).
			var a, b card
			switch {
			case r == c:
				a, b = newCard(r, 0), newCard(r, 1)
			case r > c: // suited: [high][low]
				a, b = newCard(r, 0), newCard(c, 0)
			default: // offsuit: [low][high]
				a, b = newCard(c, 0), newCard(r, 1)
			}
			tab[r][c] = estimateEquity(context.Background(), []card{a, b}, nil, 1, sims, rng)
		}
	}
	var buf bytes.Buffer
	buf.WriteString("// Code generated by TestGeneratePreflopTable; DO NOT EDIT.\n\npackage holdem\n\n")
	buf.WriteString("// preflopEquity is each starting-hand class's heads-up equity against a\n")
	buf.WriteString("// random hand. Pairs are on the diagonal, suited hands at [high][low] and\n")
	buf.WriteString("// offsuit hands at [low][high]; ranks run deuce (0) to ace (12).\n")
	buf.WriteString("var preflopEquity = [13][13]float32{\n")
	for r := 0; r < 13; r++ {
		buf.WriteString("\t{")
		for c := 0; c < 13; c++ {
			if c > 0 {
				buf.WriteString(", ")
			}
			fmt.Fprintf(&buf, "%.4f", tab[r][c])
		}
		fmt.Fprintf(&buf, "}, // %c\n", rankChars[r])
	}
	buf.WriteString("}\n")
	src, err := format.Source(buf.Bytes())
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile("preflop_table.go", src, 0o644); err != nil {
		t.Fatal(err)
	}
}
